//! Original gamemd executable outputs, generated by tools/bridge_click_oracle.py.
//! The edge test checks the isolated decision and the inverse test checks the
//! complete production scan, including camera-normalized native call fixtures.

use super::*;
use serde::Deserialize;

#[derive(Deserialize)]
struct Vectors {
    source: String,
    edge_scenarios: Vec<EdgeScenario>,
    inverse_scenarios: Vec<InverseScenario>,
}

#[derive(Deserialize)]
struct EdgeScenario {
    name: String,
    cell: [u16; 2],
    base_height: u8,
    direction_zero: bool,
    structural_cells: Vec<[u16; 2]>,
    height_overrides: Vec<[u16; 3]>,
    cases: Vec<EdgeCase>,
}

#[derive(Deserialize)]
struct EdgeCase {
    world_input: [f32; 2],
    scan_y: f32,
    expected: EdgeExpected,
}

#[derive(Deserialize)]
struct EdgeExpected {
    kind: String,
    adjusted_scan_y: f32,
    cell: Option<[u16; 2]>,
}

#[derive(Deserialize)]
struct InverseScenario {
    name: String,
    base_height: u8,
    bounds: [u16; 4],
    bridge_cells: Vec<[u16; 4]>,
    height_overrides: Vec<[u16; 3]>,
    cases: Vec<InverseCase>,
}

#[derive(Deserialize)]
struct InverseCase {
    name: String,
    world_input: [f32; 2],
    viewport: [f32; 2],
    expected_cell: [u16; 2],
}

fn vectors() -> Vectors {
    let vectors: Vectors = serde_json::from_str(crate::test_fixture::text(
        "tools/bridge_click_oracle/vectors.json",
    ))
    .unwrap();
    assert_eq!(vectors.source, "unicorn/gamemd.exe");
    vectors
}

#[test]
fn bridge_candidate_decisions_match_original_executable() {
    let vectors = vectors();
    assert_eq!(vectors.edge_scenarios.len(), 9);
    let mut count = 0;
    for scenario in vectors.edge_scenarios {
        let [cx, cy] = scenario.cell;
        let mut heights = BTreeMap::new();
        for x in cx - 1..=cx + 1 {
            for y in cy - 1..=cy + 1 {
                heights.insert((x, y), scenario.base_height);
            }
        }
        for [x, y, z] in scenario.height_overrides {
            heights.insert((x, y), z as u8);
        }
        let bridges = scenario
            .structural_cells
            .iter()
            .map(|&[x, y]| {
                (
                    (x, y),
                    TacticalBridgeCell {
                        structural: true,
                        direction_zero: scenario.direction_zero,
                    },
                )
            })
            .collect::<BTreeMap<_, _>>();
        for case in scenario.cases {
            let mut adjusted = case.scan_y - f32::from(scenario.base_height as i8) * HEIGHT_STEP;
            let actual = apply_tactical_bridge_inverse(
                case.world_input[0],
                case.world_input[1],
                case.scan_y,
                cx,
                cy,
                scenario.base_height,
                TacticalInverseContext {
                    height_map: &heights,
                    bridge_cells: Some(&bridges),
                    viewport_offset_x: 0.0,
                    viewport_offset_y: 0.0,
                },
                &mut adjusted,
            );
            let expected = match case.expected.kind.as_str() {
                "scan" => None,
                "direct" => {
                    let [x, y] = case.expected.cell.unwrap();
                    Some(TacticalInverseResult::Cell {
                        rx: x as f32,
                        ry: y as f32,
                    })
                }
                other => panic!("unknown native outcome {other}"),
            };
            assert_eq!(actual, expected, "{} {:?}", scenario.name, case.world_input);
            assert_eq!(
                adjusted, case.expected.adjusted_scan_y,
                "{} {:?}",
                scenario.name, case.world_input
            );
            count += 1;
        }
    }
    assert_eq!(count, 1782);
}

#[test]
fn complete_bridge_inverse_matches_original_executable() {
    let vectors = vectors();
    assert_eq!(vectors.inverse_scenarios.len(), 2);
    let mut count = 0;
    for scenario in vectors.inverse_scenarios {
        let [xmin, ymin, xmax, ymax] = scenario.bounds;
        let mut heights = BTreeMap::new();
        for x in xmin..=xmax {
            for y in ymin..=ymax {
                heights.insert((x, y), scenario.base_height);
            }
        }
        for [x, y, z] in scenario.height_overrides {
            heights.insert((x, y), z as u8);
        }
        let bridges = scenario
            .bridge_cells
            .iter()
            .map(|&[x, y, _, direction]| {
                (
                    (x, y),
                    TacticalBridgeCell {
                        structural: true,
                        direction_zero: direction != 0,
                    },
                )
            })
            .collect::<BTreeMap<_, _>>();
        for case in scenario.cases {
            // Native camera offsets have already been removed in world_input.
            // Exercise the viewport subtraction as well as the zero-offset API.
            for viewport in [[0.0, 0.0], case.viewport] {
                let result = screen_to_cell_tactical_inverse(
                    case.world_input[0] + viewport[0],
                    case.world_input[1] + viewport[1],
                    TacticalInverseContext {
                        height_map: &heights,
                        bridge_cells: Some(&bridges),
                        viewport_offset_x: viewport[0],
                        viewport_offset_y: viewport[1],
                    },
                );
                let (rx, ry) = match result {
                    TacticalInverseResult::Cell { rx, ry } => (rx, ry),
                    TacticalInverseResult::Fallback { .. } => {
                        panic!("unexpected fallback {} {}", scenario.name, case.name)
                    }
                };
                assert_eq!(
                    [rx.round() as u16, ry.round() as u16],
                    case.expected_cell,
                    "{} {} {:?}",
                    scenario.name,
                    case.name,
                    viewport
                );
            }
            count += 1;
        }
    }
    assert_eq!(count, 572);
}

#[test]
fn nonbridge_inverse_quantizes_one_pixel_before_every_decision() {
    // Fractional input is VERA's zoom extension, not a claim of native zoom.
    // Integer expected cells below are explicit flat/elevated cell interiors.
    for (point, expected, level) in [
        ([150.0, 255.0], [10, 5], 0_u8),
        ([-150.0, 255.0], [5, 10], 0),
        ([150.0, 195.0], [10, 5], 4),
        ([-150.0, 195.0], [5, 10], 4),
    ] {
        let mut heights = BTreeMap::new();
        for x in 0..=24 {
            for y in 0..=24 {
                heights.insert((x, y), level);
            }
        }
        for fraction in [0.0, 0.25, 0.75] {
            let result = screen_to_cell_tactical_inverse(
                point[0] + fraction,
                point[1] + fraction,
                TacticalInverseContext {
                    height_map: &heights,
                    bridge_cells: None,
                    viewport_offset_x: 0.0,
                    viewport_offset_y: 0.0,
                },
            );
            // At zero height the bounded scan ends immediately above the
            // input row, so the normal flat result uses the fallback inverse.
            // Elevated ground must be found by the scan itself.
            let (rx, ry) = match result {
                TacticalInverseResult::Cell { rx, ry } => {
                    assert_ne!(level, 0);
                    (rx, ry)
                }
                TacticalInverseResult::Fallback { rx, ry } => {
                    assert_eq!(level, 0);
                    (rx, ry)
                }
            };
            assert_eq!([rx.round() as u16, ry.round() as u16], expected);
        }
    }
}
