//! Bridge destination regressions across the camera, tactical inverse and
//! ordinary Move command boundary. These exercise the production GPU-free
//! owners called by context_order; they do not emulate window-event delivery,
//! selection, cursor art, or unwalkable-goal fallback.

use std::collections::BTreeMap;

use crate::app::input::commands::roundtrip_ordinary_local_move;
use crate::app::match_runtime::sim_tick::{screen_point_to_world_with_camera, world_point_to_cell};
use crate::map::terrain::TacticalBridgeCell;
use crate::sim::command::{Command, CommandEnvelope};
use crate::sim::world::Simulation;

fn click_cell(
    point: (f32, f32),
    camera: (f32, f32),
    zoom: f32,
    heights: &BTreeMap<(u16, u16), u8>,
    bridges: &BTreeMap<(u16, u16), TacticalBridgeCell>,
) -> (u16, u16) {
    // Only the test's forward view transform is local. Its inverse and the
    // world -> cell resolution are the same owners used by tactical orders.
    let screen = ((point.0 - camera.0) * zoom, (point.1 - camera.1) * zoom);
    let world = screen_point_to_world_with_camera(screen, camera, zoom);
    world_point_to_cell(world.0, world.1, heights, Some(bridges))
}

fn ordinary_move(
    sim: &Simulation,
    owner: crate::sim::intern::InternedId,
    entity_id: u64,
    goal: (u16, u16),
) -> CommandEnvelope {
    let issued = CommandEnvelope::new(
        owner,
        sim.session.tick,
        Command::Move {
            entity_id,
            target_rx: goal.0,
            target_ry: goal.1,
            queue: false,
            group_id: None,
        },
    );
    // The active ordinary-click path calls this in context_order::finish_order.
    // It encodes and decodes the native MegaMission record (4C6860), rather than
    // allowing a test-only semantic command to bypass destination serialization.
    let decoded = roundtrip_ordinary_local_move(sim, issued.clone())
        .expect("ordinary Move must survive its native record codec");
    assert_eq!(decoded, issued, "the codec must preserve the clicked cell");
    decoded
}

/// Rendering can scroll left of world X=0. Camera/zoom arithmetic must retain
/// the containing native world pixel for both signs; fractional zoom itself is
/// a VERA extension, not a native YR parity claim.
#[test]
fn camera_transform_retains_fractional_negative_world_pixels() {
    for (screen, camera, zoom, expected) in [
        ((36.0, 61.0), (-100.0, 200.0), 1.0, (-64.0, 261.0)),
        ((53.0, 105.0), (-100.75, 200.25), 2.0, (-74.25, 252.75)),
        ((40.0, 80.0), (-100.25, 200.5), 1.25, (-68.25, 264.5)),
        ((30.0, 60.0), (-100.25, 200.5), 0.75, (-60.25, 280.5)),
    ] {
        assert_eq!(
            screen_point_to_world_with_camera(screen, camera, zoom),
            expected,
            "camera={camera:?}, zoom={zoom}"
        );
    }
}

fn commandable_movers() -> (Simulation, crate::sim::intern::InternedId, [u64; 2]) {
    use crate::map::entities::EntityCategory;
    use crate::sim::components::Health;
    use crate::sim::game_entity::GameEntity;
    use crate::sim::house_state::HouseState;

    let mut sim = Simulation::new();
    let owner = sim.interner.intern("Americans");
    sim.houses
        .insert(owner, HouseState::new(owner, 0, None, false, 0, 10));
    sim.session.house_order = vec![owner];
    sim.session.tick = 123;
    for (id, type_name, category) in [
        (42, "MTNK", EntityCategory::Unit),
        (43, "E1", EntityCategory::Infantry),
    ] {
        let type_ref = sim.interner.intern(type_name);
        let mut entity = GameEntity::new_at_frame_zero_for_test(
            id,
            60,
            60,
            0,
            0,
            owner,
            Health { current: 100 },
            type_ref,
            category,
            0,
            5,
            false,
        );
        entity.lifecycle.in_limbo = false;
        sim.entities_mut().insert(entity);
    }
    (sim, owner, [42, 43])
}

/// Integer expected cells were generated by executing retail 6D6590, including
/// original projection and neighboring-cell lookups. The full fixture runner
/// and its limits live beside vectors.json. Fractional points and alternate
/// zooms below are separately a VERA adapter regression: they must address the
/// same containing world pixel and carry the native cell through ordinary Move.
#[test]
fn native_bridge_destinations_survive_camera_zoom_and_ordinary_move_records() {
    let fixtures: serde_json::Value = serde_json::from_str(include_str!(
        "../../../tools/bridge_click_oracle/vectors.json"
    ))
    .expect("native bridge inverse fixture JSON");
    let (mut sim, owner, movers) = commandable_movers();
    let mut cases_checked = 0;
    let mut negative_x_checked = false;
    for scenario in fixtures["inverse_scenarios"].as_array().unwrap() {
        let bounds = scenario["bounds"].as_array().unwrap();
        let mut heights = BTreeMap::new();
        for x in bounds[0].as_u64().unwrap()..=bounds[2].as_u64().unwrap() {
            for y in bounds[1].as_u64().unwrap()..=bounds[3].as_u64().unwrap() {
                heights.insert(
                    (x as u16, y as u16),
                    scenario["base_height"].as_u64().unwrap() as u8,
                );
            }
        }
        for row in scenario["height_overrides"].as_array().unwrap() {
            heights.insert(
                (
                    row[0].as_u64().unwrap() as u16,
                    row[1].as_u64().unwrap() as u16,
                ),
                row[2].as_u64().unwrap() as u8,
            );
        }
        let bridges = scenario["bridge_cells"]
            .as_array()
            .unwrap()
            .iter()
            .map(|row| {
                (
                    (
                        row[0].as_u64().unwrap() as u16,
                        row[1].as_u64().unwrap() as u16,
                    ),
                    TacticalBridgeCell {
                        structural: true,
                        direction_zero: row[3].as_i64().unwrap() != 0,
                    },
                )
            })
            .collect::<BTreeMap<_, _>>();

        for case in scenario["cases"].as_array().unwrap() {
            // Native camera/viewport variants are exercised by the oracle's
            // owner; here world-space rows feed the app's actual camera owner.
            if case["camera"] != serde_json::json!([0, 0]) {
                continue;
            }
            let point = (
                case["world_input"][0].as_f64().unwrap() as f32,
                case["world_input"][1].as_f64().unwrap() as f32,
            );
            let expected = (
                case["expected_cell"][0].as_u64().unwrap() as u16,
                case["expected_cell"][1].as_u64().unwrap() as u16,
            );
            negative_x_checked |= point.0 < 0.0;
            for (camera, zoom) in [
                ((0.0, 0.0), 1.0),
                ((217.25, 1981.5), 1.25),
                ((-2000.25, 1500.5), 0.75),
                ((217.25, 1981.5), 2.0),
            ] {
                for fraction in [0.0, 0.25, 0.5] {
                    let goal = click_cell(
                        (point.0 + fraction, point.1 + fraction),
                        camera,
                        zoom,
                        &heights,
                        &bridges,
                    );
                    assert_eq!(
                        goal, expected,
                        "{} / {}, pixel={point:?}, camera={camera:?}, zoom={zoom}, fraction={fraction}",
                        scenario["name"], case["name"]
                    );
                    for mover in movers {
                        let command = ordinary_move(&sim, owner, mover, goal);
                        sim.queue_command(command.clone());
                        assert_eq!(sim.take_due_commands(), vec![command]);
                    }
                }
            }
            cases_checked += 1;
        }
    }
    assert!(
        cases_checked >= 100,
        "native fixture coverage unexpectedly shrank"
    );
    assert!(
        negative_x_checked,
        "the opposite bridge orientation must cover negative world X"
    );
}

fn retail_dir() -> std::path::PathBuf {
    let path = std::env::var("RA2_DIR")
        .ok()
        .filter(|path| !path.trim().is_empty())
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|| {
            crate::util::config::GameConfig::load()
                .expect("set RA2_DIR or provide config.toml for this ignored test")
                .paths
                .ra2_dir
        });
    assert!(
        path.is_dir(),
        "retail directory missing: {}",
        path.display()
    );
    path
}

fn spawn_retail_mover(
    scenario: &mut crate::headless_scenario::HeadlessScenario,
    unit_type: &str,
    start: (u16, u16),
) -> (crate::sim::intern::InternedId, u64) {
    let crate::sim::runtime::SimRuntime {
        simulation: sim,
        resources,
    } = &mut scenario.runtime;
    let owner = sim.interner.intern("Americans");
    sim.houses.entry(owner).or_insert_with(|| {
        crate::sim::house_state::HouseState::new(owner, 0, None, true, 10_000, 10)
    });
    for house in sim.houses.values_mut() {
        house.multiplay_passive = true;
    }
    if !sim.session.house_order.contains(&owner) {
        sim.session.house_order.push(owner);
    }
    let entity = sim
        .spawn_object(
            unit_type,
            "Americans",
            start.0,
            start.1,
            0,
            &resources.rules,
            &resources.height_map,
        )
        .expect("retail mover spawns at the authored approach");
    sim.resolve_type_handles(&resources.rules);
    (owner, entity)
}

fn follow_clicked_goal(
    scenario: &mut crate::headless_scenario::HeadlessScenario,
    owner: crate::sim::intern::InternedId,
    entity_id: u64,
    point: (f32, f32),
    expected: (u16, u16),
    expected_on_bridge: bool,
) {
    let bridges = scenario
        .runtime
        .view()
        .resolved_terrain()
        .expect("retail terrain")
        .build_tactical_bridge_inverse_map();
    // Noninteger camera coordinates and zoom exercise the production adapter.
    let goal = click_cell(
        point,
        (-100.25, 1800.5),
        1.25,
        &scenario.runtime.resources.height_map,
        &bridges,
    );
    assert_eq!(goal, expected, "retail click {point:?}");
    let facts = scenario
        .sim()
        .path_grid()
        .and_then(|grid| grid.cell(goal.0, goal.1))
        .expect("clicked goal exists");
    assert!(facts.ground_walkable || facts.bridge_walkable);
    assert_eq!(facts.bridge_structural, expected_on_bridge);

    let admitted = super::commands::ordinary_cell_move_goal(
        scenario.sim(),
        &scenario.runtime.resources.rules,
        owner,
        entity_id,
        goal,
        true,
    )
    .expect("retail ordinary Cell input must admit the bridge destination");
    assert_eq!(
        admitted, goal,
        "retail click must keep the intended bridge/ground Cell"
    );
    let order = ordinary_move(scenario.sim(), owner, entity_id, admitted);
    scenario.runtime.simulation.queue_command(order);
    let mut arrived = false;
    for frame in 0..2_000 {
        // HeadlessScenario::tick deliberately advances an empty command batch.
        // Ordinary app frames instead drain their queued commands first (the
        // production sim_tick::advance_one_simulation_frame path). Preserve
        // that ingress here so the Move actually reaches command execution.
        let due = scenario.runtime.simulation.take_due_commands();
        let output = scenario
            .runtime
            .advance_frame(
                &due,
                crate::headless_scenario::SIM_TICK_MS,
                crate::sim::world::TickLane::Ordinary,
            )
            .expect("fixture frame must complete");
        assert!(output.tick.frame_committed, "the retail frame must commit");
        let entity = scenario
            .sim()
            .entities()
            .get(entity_id)
            .expect("mover alive");
        if frame == 0 {
            assert!(output.tick.executed_commands > 0);
            assert!(
                entity.movement_target.is_some(),
                "clicked goal {goal:?} must become a movement target after command admission"
            );
            assert_eq!(
                entity
                    .movement_target
                    .as_ref()
                    .and_then(|target| target.final_goal),
                Some(goal),
                "each chained retail command must install its exact destination"
            );
            assert_eq!(
                entity.navigation.nav_com,
                Some(crate::sim::components::NavTargetRef::cell(goal.0, goal.1)),
                "each chained retail command must also publish its exact NavCom"
            );
        }
        if (entity.position.rx, entity.position.ry) == goal && entity.movement_target.is_none() {
            // Body Cell entry can precede paid-head retirement by several
            // frames. Check the state used by the next actual Move order.
            assert_eq!(
                entity.on_bridge, expected_on_bridge,
                "clicked goal {goal:?} must select the intended movement plane"
            );
            assert_eq!(
                entity.movement_layer_or_ground(),
                if expected_on_bridge {
                    crate::sim::movement::locomotor::MovementLayer::Bridge
                } else {
                    crate::sim::movement::locomotor::MovementLayer::Ground
                }
            );
            println!(
                "retail click {point:?} -> {goal:?}: arrived after {} frames, on_bridge={}",
                frame + 1,
                entity.on_bridge
            );
            arrived = true;
            break;
        }
    }
    assert!(arrived, "ordinary Move did not reach clicked goal {goal:?}");
}

/// Real Hills terrain, rules, bridge flags and ordinary Move execution. These
/// interior lane/approach points are geometric regression controls, not native
/// path-sequence goldens. Retail input bytes are loaded without modifying them.
#[test]
#[ignore = "requires a retail RA2/YR install (RA2_DIR or config.toml)"]
fn retail_hills_clicks_drive_tank_and_gi_to_both_deck_sides_and_approaches() {
    for unit_type in ["MTNK", "E1"] {
        let mut scenario = crate::headless_scenario::load(&retail_dir(), "Hills.mmx", 0xB21D_6E51)
            .expect("Hills retail scenario loads");
        let (owner, mover) = spawn_retail_mover(&mut scenario, unit_type, (75, 74));
        for (point, goal, on_bridge) in [
            ((419.0, 2355.0), (87, 74), true),
            ((330.0, 2385.0), (87, 76), true),
            ((720.0, 2520.0), (98, 74), false),
            ((30.0, 2175.0), (75, 74), false),
        ] {
            follow_clicked_goal(&mut scenario, owner, mover, point, goal, on_bridge);
        }
    }
}

#[test]
#[ignore = "requires a retail RA2/YR install (RA2_DIR or config.toml)"]
fn retail_hills_ground_click_keeps_gi_beneath_bridge() {
    let mut scenario = crate::headless_scenario::load(&retail_dir(), "Hills.mmx", 0xB21D_6E51)
        .expect("Hills retail scenario loads");
    let (owner, mover) = spawn_retail_mover(&mut scenario, "E1", (87, 71));
    follow_clicked_goal(
        &mut scenario,
        owner,
        mover,
        (270.0, 2475.0),
        (87, 78),
        false,
    );
}

fn advance_input_fixture(sim: &mut Simulation, rules: &crate::rules::ruleset::RuleSet) {
    let due = sim.take_due_commands();
    let grid = sim.path_grid_snapshot();
    let result = sim.advance_tick(
        &due,
        Some(rules),
        &BTreeMap::new(),
        grid.as_deref(),
        None,
        67,
    );
    assert!(
        result.frame_committed,
        "ordinary scheduled frame failed: {result:?}"
    );
}

#[test]
fn ordinary_walk_cell_input_reaches_near_bank_and_valid_high_bridge() {
    for bridge in [false, true] {
        let (mut sim, rules, actor) = Simulation::walk_cell_input_test_scene(bridge);
        let owner = sim.interner.get("Local").unwrap();
        let clicked = if bridge { (9, 6) } else { (11, 5) };
        let chosen =
            super::commands::ordinary_cell_move_goal(&sim, &rules, owner, actor, clicked, true)
                .unwrap();
        if bridge {
            assert_eq!(chosen, clicked);
        } else {
            assert_ne!(chosen, clicked);
            assert!(
                chosen.0 < 8,
                "disconnected river must choose the actor's bank: {chosen:?}"
            );
        }
        let envelope = ordinary_move(&sim, owner, actor, chosen);
        sim.queue_command(envelope);
        advance_input_fixture(&mut sim, &rules);
        let e = sim.entities().get(actor).unwrap();
        assert_eq!(
            e.navigation.nav_com,
            Some(crate::sim::components::NavTargetRef::Cell {
                rx: chosen.0,
                ry: chosen.1
            })
        );
        assert!(
            e.movement_target.as_ref().unwrap().path.is_empty(),
            "command accepts before Process search"
        );
        for _ in 0..250 {
            advance_input_fixture(&mut sim, &rules);
            let e = sim.entities().get(actor).unwrap();
            if (e.position.rx, e.position.ry) == chosen
                && e.locomotor.as_ref().unwrap().step_head().is_none()
            {
                break;
            }
        }
        let e = sim.entities().get(actor).unwrap();
        assert_eq!((e.position.rx, e.position.ry), chosen, "bridge={bridge}");
        assert_eq!(e.on_bridge, bridge);
        assert!(
            e.locomotor.as_ref().unwrap().step_head().is_none(),
            "arrival must retire its paid head"
        );
    }
}

#[test]
fn encoded_walk_destination_survives_topology_change_before_due_frame() {
    let (mut sim, rules, actor) = Simulation::walk_cell_input_test_scene(true);
    let owner = sim.interner.get("Local").unwrap();
    let clicked = (9, 6);
    let chosen =
        super::commands::ordinary_cell_move_goal(&sim, &rules, owner, actor, clicked, true)
            .unwrap();
    assert_eq!(chosen, clicked);
    let mut order = ordinary_move(&sim, owner, actor, chosen);
    // The scheduler drains commands for the NEXT frame. Leave one full
    // object turn before this already-encoded destination becomes due.
    order.execute_tick = sim.session.tick + 2;
    sim.queue_command(order.clone());
    sim.close_walk_input_test_bridge(&rules);
    assert_ne!(
        super::commands::ordinary_cell_move_goal(&sim, &rules, owner, actor, clicked, true),
        Some(clicked),
        "the later input query must discriminate the changed topology"
    );
    assert!(sim.take_due_commands().is_empty());
    advance_input_fixture(&mut sim, &rules);
    advance_input_fixture(&mut sim, &rules);
    let e = sim.entities().get(actor).unwrap();
    assert_eq!(
        e.navigation.nav_com,
        Some(crate::sim::components::NavTargetRef::Cell { rx: 9, ry: 6 })
    );
    assert_eq!(
        e.movement_target.as_ref().unwrap().final_goal,
        Some(clicked)
    );
    assert!(e.movement_target.as_ref().unwrap().path.is_empty());
    // This proves exact event installation. The following failed-Process and
    // same-slot Move restart remain the separately documented open increment.
}

#[test]
fn direct_simulation_walk_move_is_an_already_resolved_destination() {
    let (mut sim, rules, actor) = Simulation::walk_cell_input_test_scene(false);
    let owner = sim.interner.get("Local").unwrap();
    assert_ne!(
        super::commands::ordinary_cell_move_goal(&sim, &rules, owner, actor, (9, 5), true),
        Some((9, 5))
    );
    sim.queue_command(CommandEnvelope::new(
        owner,
        sim.session.tick,
        Command::Move {
            entity_id: actor,
            target_rx: 9,
            target_ry: 5,
            queue: false,
            group_id: None,
        },
    ));
    advance_input_fixture(&mut sim, &rules);
    let e = sim.entities().get(actor).unwrap();
    assert_eq!(
        e.navigation.nav_com,
        Some(crate::sim::components::NavTargetRef::Cell { rx: 9, ry: 5 })
    );
    assert_eq!(e.movement_target.as_ref().unwrap().final_goal, Some((9, 5)));
}
